### PR TITLE
Browser disc button

### PR DESCRIPTION
**Pull request by DevRhyse**
# Description

Was receiving error related to #277 

Was getting error due to import LoginWithDiscord from "features/auth/LoginWithDiscord"; already having a button being returned to this file and nested inside of another button element.

Replaced the button element with a div element and placed the imported LoginWithDiscord 

## Type of change

Please select everything applicable. Please, do not delete any lines.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Issue
- [x] Is this related to a specific issue? Is so please specify: #277 

# Checklist:

- [x] This PR is up to date with the development branch, and merge conflicts have been resolved
- [x] I have executed `npm run lint` and resolved any outstanding errors. Most issues can be solved by executing `npm run format`
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Caleb-Cohen** [comment]
I plan on rebasing this anyways, but any particular reason you're pulled from @isaaclee12's branch?

**Comment by Caleb-Cohen** [comment]
Rebased to #286

**Comment by DevRhyse** [comment]
I have no idea. I did something wrong I assume. I thought I created a new branch before I did anything

**Comment by Caleb-Cohen** [comment]
> I have no idea. I did something wrong I assume. I thought I created a new branch before I did anything

Maybe you made a new branch and didn't check out? Regardless, pretty painless for a single commit, but something you may want to look into!

**Comment by DevRhyse** [comment]
> > I have no idea. I did something wrong I assume. I thought I created a new branch before I did anything
> 
> Maybe you made a new branch and didn't check out? Regardless, pretty painless for a single commit, but something you may want to look into!

For sure! Thank you for making me aware of this.

**Comment by isaaclee12** [comment]
@DevRhyse @Caleb-Cohen Hi. This is my bad, I had Rhyse switch his remote "origin" to point to my repository. Guessing it never got switched back to his. Regardless, since it's an independent branch it shouldn't be a problem.

Rhyse, if you want to set your GitHub to point to your own director, make sure to run ```git remote set-url origin [your fork url]``` in VSCode.

**Pull request closed without merging**
