### PR TITLE
Welcome user component

### PR DESCRIPTION
**Pull request by code2244**
# Description

Created a WelcomeUser component that takes in user's displayName as props to display a welcome message. 

## Type of change

Please select everything applicable. Please, do not delete any lines.

- [x] New feature (non-breaking change which adds functionality)

## Issue
- [x] Is this related to a specific issue? Is so please specify: #203 Create a WelcomeUser component to greet Together's user 

# Checklist:

- [x] I have executed `npm run lint` and resolved any outstanding errors. Most issues can be solved by executing `npm run format`
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Caleb-Cohen** [comment]
@code2244 I'm having difficulty getting the modal popup when accessing Together. How is it triggered?

**Comment by code2244** [comment]
Oh I did not saw any specifications for creating a modal in the issue, I think is an issue to refactor the code of the welcome message at the top left corner of the landing page but I can create the modal if is what is needed.

**Comment by Caleb-Cohen** [comment]
If we need to wait until the Modal is updated. That works as well.

**Comment by code2244** [comment]
perfect, I will work in the modal.

**Comment by Caleb-Cohen** [comment]
Discussed with @code2244 the necessary changes for this issue.

**Pull request closed without merging**
