### PR TITLE
Trizz 202 refactor pages components into a pages folder/ Rejection Modal Code C&P below line 23

### PR DESCRIPTION
**Pull request by TrizzIzBizy**
#202 1-2 Commits  on this issue

Relocate CalendarPage Component to newly created "pages" folder  within client/src
Copied the rejection modal code  and pasted under line 23 (linting should improve continuity I imagine)

## Type of change

Please select everything applicable. Please, do not delete any lines.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Issue
- [ ] Is this related to a specific issue? Is so please specify: Issue #202 

# Checklist:

- [x] This PR is up to date with the development branch, and merge conflicts have been resolved
- [ ] I have executed `npm run lint` and resolved any outstanding errors. Most issues can be solved by executing `npm run format`
- [x] My code follows the style guidelines of this project (discrepancies should be captured by linting)
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by JoeDravarol** [comment]
Hey @TrizzIzBizy, is this completed? I remember you had issue with `npm install` which halted your work.

**Comment by Caleb-Cohen** [comment]
Hey there @TrizzIzBizy!

I tested this out locally and ran into errors regarding the calendarPage. Is this still a work in progress?

**Comment by TrizzIzBizy** [comment]
> Hey there @TrizzIzBizy!
> 
> I tested this out locally and ran into errors regarding the calendarPage. Is this still a work in progress?

Hi @Caleb-Cohen - I wasn't aware.  Were there simple errors like syntax error rules or, more complex?  Yes, it appears so.

**Comment by Caleb-Cohen** [comment]
Screenshot 2023-02-02 at 4 21 28 PM
Screenshot 2023-02-02 at 4 21 52 PM

@TrizzIzBizy - Looks like there errors culminating from the calendarPage being commented out.

**Comment by Caleb-Cohen** [comment]
Hey @TrizzIzBizy just checking in on how you would this PR handled. Thank you!

**Pull request closed without merging**
