### PR TITLE
change attribute name 'class' -> 'className'

### PR DESCRIPTION
**Pull request by timtom619**
# Description

Current change fixes the attribute name from "class" -> "className" in the following files:

- client/src/features/form/FormCreateEvent.js
- client/src/features/form/FormScheduleEvent.js
- client/src/features/home/LogoContainer.js
- client/src/features/home/NavButtons.js

## Type of change

Please select everything applicable. Please, do not delete any lines.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Issue
- [x] Is this related to a specific issue? Is so please specify:

# Checklist:

- [x] This PR is up to date with the development branch, and merge conflicts have been resolved
- [x] I have executed `npm run lint` and resolved any outstanding errors. Most issues can be solved by executing `npm run format`
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by timtom619** [comment]
change closes #296

**Review by MatthewBozin — APPROVED** [review]

**Comment by timtom619** [comment]
@Caleb-Cohen I went ahead and synced my feature branch with development. Let me know if there is anything else I can do. Thanks, guys!

**Comment by Caleb-Cohen** [comment]
> @Caleb-Cohen I went ahead and synced my feature branch with development. Let me know if there is anything else I can do. Thanks, guys!

I'm not seeing a new commit on this PR. Did you push those changes to your fix-browser-console-warning--#276 branch?

**Comment by timtom619** [comment]
@Caleb-Cohen @MatthewBozin Should be good now. I thought it was pushed, sorry for the confusion.

**Comment by Caleb-Cohen** [comment]
Hey there @timtom619 looking at the updated commits it looks like it's brought in a bunch of new commits that aren't directly relevant to this PR. This is not the expected behavior of a sync to development. This is not the first time it's occurred, and we're trying to understand why it happens so I can update the instructions to avoid this.

Can you walk me through you how you synced `fix-browser-console-warning` with `development`?

@RascalTwo @timmyichen any insight on why this continues to happen would be appreciated. I'll rebase commit [e3f38f84](https://github.com/Caleb-Cohen/Together/pull/296/commits/e3f38f8478fe88011bf7376b41a1b4875c30cabf#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519) and remove the package-lock changes later today.

**Comment by timtom619** [comment]
Sure thing, I first tried going into my fork on the fix-browser-console-warning branch and pressing the "Sync fork", but nothing was updating. Then in the terminal, I did the following:
1. git checkout development
2.  git pull origin
3. git checkout fix-browser-console-warning---#276
4. git merge development
5. resolved merge conflicts (leaving package.json.lock unchanged)
6. git push -u origin fix-browser-console-warning---#276

I think steps 2 - 4 are where it brought in the updated commits from the dev branch. Let me know if this was the incorrect way of doing this. If so I apologize and will reach out beforehand. 
@Caleb-Cohen

**Comment by Caleb-Cohen** [comment]
> Sure thing, I first tried going into my fork on the fix-browser-console-warning branch and pressing the "Sync fork", but nothing was updating. Then in the terminal, I did the following:
> 
> 1. git checkout development
> 2. git pull origin
> 3. git checkout fix-browser-console-warning---[Fix browser console warning (class -> className) #276](https://github.com/Caleb-Cohen/Together/issues/276)
> 4. git merge development
> 5. resolved merge conflicts (leaving package.json.lock unchanged)
> 6. git push -u origin fix-browser-console-warning---[Fix browser console warning (class -> className) #276](https://github.com/Caleb-Cohen/Together/issues/276)
> 
> I think steps 2 - 4 are where it brought in the updated commits from the dev branch. Let me know if this was the incorrect way of doing this. If so I apologize and will reach out beforehand. @Caleb-Cohen

I believe `git pull origin` should only pull the current version of the `development` branch in your repository. Was your development branch on github up to date with development branch in my repository at the time `git pull origin` was executed?

**Comment by Caleb-Cohen** [comment]
Updated PR can be found #318

**Pull request closed without merging**
