### PR TITLE
fix #281. Add test user to the database

### LINKED ISSUE #281: Modal doesn't show up on events created by mock user
## Describe the bug

The modal doesn't show up when an event is created using a mock user.

## To Reproduce
1. Create an event while logged in as a mock user
2. It is added to the database
3. Try to open the event
4. See the error

## Expected behavior
The modal should open

## Which Branch should this fix be Pulled into?
PR into development

## Additional context

*If you're interested in working on this feature, please comment so you can be assigned*

### PR DESCRIPTION
**Pull request by romanstetsyk**
# Description

Add the test user to the database to correctly show modals.

## Type of change

Please select everything applicable. Please, do not delete any lines.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Issue
- [x] Is this related to a specific issue? Is so please specify: #281 

# Checklist:

- [x] This PR is up to date with the development branch, and merge conflicts have been resolved
- [x] I have executed `npm run lint` and resolved any outstanding errors. Most issues can be solved by executing `npm run format`
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by intelagense** [comment]
When displaying the event modal, would this PR expose the discord names and discriminators to non-authenticated users?

**Comment by romanstetsyk** [comment]
Yes. This PR only fixes the bug that when an event is created using a mock user (file located at `server/config/mockUser.json`), you can't open it.

**Comment by intelagense** [comment]
Ah, so only the mock data would be exposed on the localhost?

**Comment by romanstetsyk** [comment]
Discord names will continue to be displayed like on this screenshot 
image

**Comment by intelagense** [comment]
Ok, I was getting confused too. I have reworded the title of #279 for clarity

**Comment by romanstetsyk** [comment]
I realized I linked the wrong issue in the commit, so it's displayed under #279 too

**Comment by Caleb-Cohen** [comment]
Good work!

**Pull request merged**
