### PR TITLE
Plus date interface

### PR DESCRIPTION
**Pull request by DevRhyse**
# Description

When the plus button was clicked originally, it would only show the current year.
Now when the plus button is clicked it adds the month and date of the clicked date on the calendar. 
Changed onClick in the dayCard.js File
Edited FormProvider in calendarPage.js file. Removed React fragment and interchanged it with  FormProvider

## Type of change

Please select everything applicable. Please, do not delete any lines.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Issue
- [X] Is this related to a specific issue? If so, please specify: #304 

# Checklist:

- [X] This PR is up to date with the development branch, and merge conflicts have been resolved
- [X] I have executed `npm run lint` and resolved any outstanding errors. Most issues can be solved by executing `npm run format`
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by RascalTwo** [comment]
Looks good, well done you two!

https://user-images.githubusercontent.com/9403665/216741046-1116ef59-6af2-47eb-becd-eb5dfdc22706.mp4

**Comment by DevRhyse** [comment]
> Looks good, well done you two!
> 
>  initial-date-is-clicked.mp4

Thank you! We couldn't have finished without you, we were pretty stuck at that spot and didn't know how to progress forward.

**Comment by Caleb-Cohen** [comment]
Great work @DevRhyse @AitchGrasso!

Is it possible to have the same logic added to the end date? Since the modal defaults to non-recurring the start date and end date will be the same. 

Screenshot 2023-02-07 at 10 25 16 AM

**Comment by DevRhyse** [comment]
Good point! I didn't think of this, to begin with. I'm sure it would be an easy fix. Do you want me to remake the pull request when it's adjusted? Or how would this work?

**Comment by DevRhyse** [comment]
> Great work @DevRhyse @AitchGrasso!
> 
> Is it possible to have the same logic added to the end date? Since the modal defaults to non-recurring the start date and end date will be the same.
> 
> Screenshot 2023-02-07 at 10 25 16 AM

Good point! I didn't think of this, to begin with. I'm sure it would be an easy fix. Do you want me to remake the pull request when it's adjusted? Or how would this work?

**Comment by Caleb-Cohen** [comment]
> > Great work @DevRhyse @AitchGrasso!
> > Is it possible to have the same logic added to the end date? Since the modal defaults to non-recurring the start date and end date will be the same.
> > Screenshot 2023-02-07 at 10 25 16 AM
> 
> Good point! I didn't think of this, to begin with. I'm sure it would be an easy fix. Do you want me to remake the pull request when it's adjusted? Or how would this work?

Pull request does not need to be remade. 

If you push more code to the `plusDateInterface` branch in your repository this PR will be automatically updated.

**Comment by DevRhyse** [comment]
> > > Great work @DevRhyse @AitchGrasso!
> > > Is it possible to have the same logic added to the end date? Since the modal defaults to non-recurring the start date and end date will be the same.
> > > Screenshot 2023-02-07 at 10 25 16 AM
> > 
> > 
> > Good point! I didn't think of this, to begin with. I'm sure it would be an easy fix. Do you want me to remake the pull request when it's adjusted? Or how would this work?
> 
> Pull request does not need to be remade.
> 
> If you push more code to the `plusDateInterface` branch in your repository this PR will be automatically updated.

Should be fixed now

**Comment by Caleb-Cohen** [comment]
Looks good! Thank you.

**Pull request merged**
