### PR TITLE
Add Proxy to Event Form

### PR DESCRIPTION
**Pull request by MatthewBozin**
Addresses #35 

- Changes
Added port 2121 proxy to frontend package.json. 
Removed baseURL from DataService URL. 
Uninstalled cors and removed cors whitelist from server.js.

### CODE REVIEW

**Comment by JoeDravarol** [comment]
Just curious, does the proxy works without cors? We are able to submit events to the server without any Cross origin error?

**Comment by MatthewBozin** [comment]
It does work without cors! Here is a [helpful article](https://levelup.gitconnected.com/overview-of-proxy-server-and-how-we-use-them-in-react-bf67c062b929) that goes over how create-react-app handles proxies!

**Comment by JoeDravarol** [comment]
Awesome! That's good to know.

**Comment by Caleb-Cohen** [comment]
Can someone explain to me how the data flows once I submit an event form?

**Comment by MatthewBozin** [comment]
What proxy accomplishes: Browsers have cross-origin limitations that block API requests from sites running on localhost. Proxy servers can assist in redirecting requests to APIs without having to go via the browser’s default request options, which helps to evade several cross-origin limitations. From [this article](https://blog.logrocket.com/why-you-should-use-proxy-server-create-react-app/)

**Comment by MatthewBozin** [comment]
Data flow:
- The handleSubmit() function in UserForm.js takes userData and calls the Data Sevice's create() method, with userData as the argument. 
- The Data Service's create() method makes a POST request using Axios to '/events/create', sending userData as the request's msg. The proxy makes the request originate from localhost 2121, so it bypasses cross-origin restrictions, since the server is also on localhost 2121.
- The server receives this request and routes it to the 'events' route, to the 'create' method of the events controller, which creates a new document of the Event schema and saves it in MongoDB.

**Comment by Caleb-Cohen** [comment]
Why can't the POST request originate from the 2121? Why do we have to proxy into 2121?

**Review by Caleb-Cohen — APPROVED** [review]

**Pull request merged**
