### PR TITLE
Feature/issue 309

### PR DESCRIPTION
**Pull request by romanstetsyk**
# Description

Add the user's timezone to the modal when an event is created or displayed.

## Type of change

Please select everything applicable. Please, do not delete any lines.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Issue
- [x] Is this related to a specific issue? If so, please specify: #309 

# Checklist:

- [x] This PR is up to date with the development branch, and merge conflicts have been resolved
- [x] I have executed `npm run lint` and resolved any outstanding errors. Most issues can be solved by executing `npm run format`
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by romanstetsyk** [comment]
A lot of changes come from running prettier. The actual code that is added is in the first commit. Feel free to change the icon or text formatting!

**Review by MatthewBozin — APPROVED** [review]
This looks good, well done!
Only nitpick I can find is that the displayed timezone value has underscores instead of spaces, but it would give us a good opportunity to make a 100Devs-Good-First-Issue to fix that, so I'm happy to merge this as-is!

**Comment by Caleb-Cohen** [comment]
Some of these changes are lint doing it's thing, yeah?

**Comment by romanstetsyk** [comment]
Yeah, for actual changes look at the first commit

**Pull request merged**
