### PR TITLE
Bugfix/event times

### PR DESCRIPTION
**Pull request by isaaclee12**
# Description

Resolution for Issue #261:

- Changed UI of Date/Time entry fields to be more intuitive
- Able to enter start and end date for non-recurring events again
- End date value is set to start date's value automatically, but the end date can be set independently while the start date stays the same (This is for convenience, and to allow datetimes for non-recurring events that fall on two subsequent dates).

## Type of change

Please select everything applicable. Please, do not delete any lines.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Issue
- [X] Is this related to a specific issue? Is so please specify: #261
 

# Checklist:

- [X ] I have executed `npm run lint` and resolved any outstanding errors. Most issues can be solved by executing `npm run format`
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by Caleb-Cohen** [comment]
@isaaclee12 any idea why there's a bunch of commits included that are not relevant to this PR?

**Comment by isaaclee12** [comment]
> @isaaclee12 any idea why there's a bunch of commits included that are not relevant to this PR?

I have no idea. @timmyichen mentioned using squash and merge if you just want to take the last commit instead of the entire commit history, in case you want to avoid bloating the git history. 
image

**Comment by timmyichen** [comment]
> > @isaaclee12 any idea why there's a bunch of commits included that are not relevant to this PR?
> 
> I have no idea. @timmyichen mentioned using squash and merge if you just want to take the last commit instead of the entire commit history, in case you want to avoid bloating the git history. 
> image
> 

Have you already tried rebasing off development?

**Comment by isaaclee12** [comment]
> > > @isaaclee12 any idea why there's a bunch of commits included that are not relevant to this PR?
> > 
> > 
> > I have no idea. @timmyichen mentioned using squash and merge if you just want to take the last commit instead of the entire commit history, in case you want to avoid bloating the git history.
> > image
> 
> Have you already tried rebasing off development?

I did try using rebase at some point (how i did so is complicated). Long story short, I bungled the whole process and honestly is probably how those random commits ended up in this branch.

**Comment by timmyichen** [comment]
it might be a good learning experience to try to rebase this together, but if the files changed are what you would expect it shouldn't matter (other than polluting the commit history a bit)

**Comment by Caleb-Cohen** [comment]
> it might be a good learning experience to try to rebase this together, but if the files changed are what you would expect it shouldn't matter (other than polluting the commit history a bit)

I'm interested in giving this a try! Would you have some time to lifeguard this evening or after standup tomorrow?

**Comment by timmyichen** [comment]
Either one works!

**Pull request merged**
