### PR TITLE
Redirect user to calendarPage on login

### PR DESCRIPTION
**Pull request by jalonghurst**
# Description
LoginWIthDiscord.js file is modified so that on login the user is redirected from landingPage to calendarPage.

## Type of change

Please select everything applicable. Please, do not delete any lines.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Issue
'Redirect user to Calendar when user logs in' #268
# Checklist:

- [ ] I have executed `npm run lint` and resolved any outstanding errors. Most issues can be solved by executing `npm run format`
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Caleb-Cohen** [comment]
Tested and it works. My only concern is that this prevents users from accessing the landing page when logged in. Would it be possible to have login redirect to the calendar page, but not lock a logged-in user from the calendar? 

Tagging @MatthewBozin for visibility and he originally created the issue.

**Comment by jalonghurst** [comment]
Yes I see, the logged in user cannot access 'Home' from the calendar. I'll take another look at this!

**Comment by jalonghurst** [comment]
It seems to work now, there is freedom to move to any page whether logged in or not. :)

Whilst trying to fix it, I also worked out how to redirect to the landing page when the user logs out, so I've left that code in the logout function in useProvideAuth.js just in case it is desired, happy to remove it if not!

**Comment by jalonghurst** [comment]
It appears to be working now! I also added code to redirect to the landing page on logout, in case that's desired but I'm happy to remove it if not, let me know if there's a better way of doing it and I'll give it another go

**Comment by MatthewBozin** [comment]
The code looks good to me, tested it and everything works! 
I'm curious about the line spacing, was that due to a linter you are using? Would you mind altering your line spacing to have it conform with the rest of the codebase?
Otherwise, this looks ready to merge.

**Comment by jalonghurst** [comment]
That's great! I have removed those empty spaces now. Sorry this was overlooked as I was adding and removing an if statement when I was trying to get the useEffect hook to work. Many thanks

**Comment by Caleb-Cohen** [comment]
> That's great! I have removed those empty spaces now. Sorry this was overlooked as I was adding and removing an if statement when I was trying to get the useEffect hook to work. Many thanks

Great work!

**Pull request merged**
